/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JobApplication } from "./JobApplication";
import { JobApplicationCountArgs } from "./JobApplicationCountArgs";
import { JobApplicationFindManyArgs } from "./JobApplicationFindManyArgs";
import { JobApplicationFindUniqueArgs } from "./JobApplicationFindUniqueArgs";
import { DeleteJobApplicationArgs } from "./DeleteJobApplicationArgs";
import { JobApplicationService } from "../jobApplication.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => JobApplication)
export class JobApplicationResolverBase {
  constructor(
    protected readonly service: JobApplicationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "JobApplication",
    action: "read",
    possession: "any",
  })
  async _jobApplicationsMeta(
    @graphql.Args() args: JobApplicationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [JobApplication])
  @nestAccessControl.UseRoles({
    resource: "JobApplication",
    action: "read",
    possession: "any",
  })
  async jobApplications(
    @graphql.Args() args: JobApplicationFindManyArgs
  ): Promise<JobApplication[]> {
    return this.service.jobApplications(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => JobApplication, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "JobApplication",
    action: "read",
    possession: "own",
  })
  async jobApplication(
    @graphql.Args() args: JobApplicationFindUniqueArgs
  ): Promise<JobApplication | null> {
    const result = await this.service.jobApplication(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => JobApplication)
  @nestAccessControl.UseRoles({
    resource: "JobApplication",
    action: "delete",
    possession: "any",
  })
  async deleteJobApplication(
    @graphql.Args() args: DeleteJobApplicationArgs
  ): Promise<JobApplication | null> {
    try {
      return await this.service.deleteJobApplication(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
